# Generated by Django 4.2.7 on 2023-11-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=10)),
                ('jobtype', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time')], default='FT', max_length=10)),
                ('qualifications', models.TextField()),
                ('skills', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=14, unique=True)),
            ],
        ),
    ]
